#!/usr/bin/env bash

source /root/shovel/plugins/okfail

if [[ -f $1 ]]; then
	ok "File $1 is in place." "$DESCRIPTION" "$ENVIRONMENT"
else
	fail "File $1 is not in place!" "$DESCRIPTION" "$ENVIRONMENT"
fi
